spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SPdemo
    username: postgres
    password: 25062001Zh
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-bean-definition-overriding: true
